version: "3"

services:
  wildfly:
    image: quay.io/wildfly/wildfly:latest
    ports:
      - "19990:9990"
      - "19980:8080"
    entrypoint: '/bin/bash -c'
    command:
      - |
        /opt/jboss/wildfly/bin/add-user.sh admin welcome1 --silent
        /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0

  db:
    image: postgres
    restart: always
    volumes:
      - './db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
    environment:
      POSTGRES_PASSWORD: easylogin_pass
      POSTGRES_USER: easylogin_user
      POSTGRES_DB: easylogin_db
